name: norm_rl
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - alembic=1.18.0=pyhcf101f3_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - bottle=0.13.4=pyhe01879c_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.10.1=pyh707e725_0
  - cpython=3.13.11=py313hd8ed1ab_101
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=hbcb9cd8_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.19=py313hb7f33ac_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - ffmpeg=8.0.1=gpl_hf567e27_909
  - filelock=3.20.3=pyhd8ed1ab_0
  - fmt=12.1.0=hff5e90c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - glslang=16.1.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h86d8783_2
  - graphite2=1.3.14=hecca717_2
  - greenlet=3.3.0=py313h7033f15_0
  - gymnasium=1.0.0=np2py313h6b35a55_2
  - harfbuzz=12.3.0=h6083320_0
  - icu=78.2=h33c6efd_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.27.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libass=0.17.4=h96ad9f0_0
  - libblas=3.11.0=5_h5875eb1_mkl
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_hfef963f_mkl
  - libcublas=12.9.1.4=h676940d_1
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcudss=0.7.1.4=h58dd1b1_1
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcurand=10.3.10.19=h676940d_1
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h5e43f62_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=ha7672b3_6
  - libmpdec=4.0.0=hb03c661_1
  - libnl=3.11.0=hb9d3cd8_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=hecca717_2
  - libogg=1.3.5=hd0c01bc_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopengl-devel=1.7.0=ha4b6fd6_2
  - libopenvino=2025.4.1=hb56ce9e_1
  - libopenvino-auto-batch-plugin=2025.4.1=hd85de46_1
  - libopenvino-auto-plugin=2025.4.1=hd85de46_1
  - libopenvino-hetero-plugin=2025.4.1=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.4.1=hb56ce9e_1
  - libopenvino-intel-gpu-plugin=2025.4.1=hb56ce9e_1
  - libopenvino-intel-npu-plugin=2025.4.1=hb56ce9e_1
  - libopenvino-ir-frontend=2025.4.1=hd41364c_1
  - libopenvino-onnx-frontend=2025.4.1=h1862bb8_1
  - libopenvino-paddle-frontend=2025.4.1=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.4.1=hecca717_1
  - libopenvino-tensorflow-frontend=2025.4.1=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.4.1=hecca717_1
  - libopus=1.6.1=h280c20c_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.54=h421ea60_0
  - libpq=18.1=hb80d175_3
  - libprotobuf=6.31.1=h49aed37_4
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc7d488a_2
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.9.1=cpu_mkl_hb142093_104
  - libudev1=258.3=h6569c3e_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.13=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.15.2=hecca717_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.8=h4922eb0_0
  - mako=1.3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - mkl=2025.3.0=h0e700b2_463
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nccl=2.29.2.1=h4d09622_2
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.1=py313hf6604e3_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_1
  - optree=0.18.0=py313h7037e92_0
  - optuna=4.6.0=pyhd8ed1ab_0
  - optuna-dashboard=0.20.0=pyhd8ed1ab_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - psycopg2=2.9.11=py313hdc942f6_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - pybind11=3.0.1=pyh97977ab_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pyglet=2.0.20=pyhd8ed1ab_0
  - pyopengl=3.1.10=pyha804496_2
  - python=3.13.11=hc97d973_100_cp313
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python_abi=3.13=8_cp313
  - pytorch=2.9.1=cpu_mkl_py313_hc56ae27_104
  - pyyaml=6.0.3=py313h3dea7bd_1
  - rdma-core=60.0=hecca717_0
  - readline=8.3=h853b02a_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.30=h3b84278_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.5=h3e344bc_0
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - sqlalchemy=2.0.45=py313h07c4f96_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=hb700be7_2
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.4.0=pyhcf101f3_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - triton=3.5.1=cuda129py313h246eb7c_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.47=hd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - DataProperty==1.1.0
    - ImageIO==2.37.2
    - Markdown==3.10
    - Pygments==2.19.2
    - Shimmy==2.0.0
    - Werkzeug==3.1.5
    - absl-py==2.3.1
    - aiofiles==25.1.0
    - ale-py==0.11.2
    - certifi==2026.1.4
    - chardet==5.2.0
    - charset-normalizer==3.4.4
    - chex==0.1.91
    - contourpy==1.3.3
    - cycler==0.12.1
    - decorator==5.2.1
    - etils==1.13.0
    - flax==0.12.2
    - fonttools==4.61.1
    - grpcio==1.76.0
    - hf-xet==1.2.0
    - huggingface-hub==0.36.0
    - huggingface-sb3==3.0
    - humanize==4.15.0
    - idna==3.11
    - imageio-ffmpeg==0.6.0
    - importlib_resources==6.5.2
    - jax==0.8.2
    - jaxlib==0.8.2
    - kiwisolver==1.4.9
    - markdown-it-py==4.0.0
    - matplotlib==3.10.8
    - mbstrdecoder==1.1.4
    - mdurl==0.1.2
    - ml_dtypes==0.5.4
    - moviepy==2.2.1
    - msgpack==1.1.2
    - nest-asyncio==1.6.0
    - numpy==2.2.6
    - opencv-python==4.12.0.88
    - opt_einsum==3.4.0
    - optax==0.2.6
    - orbax-checkpoint==0.11.31
    - pandas==2.3.3
    - pathvalidate==3.3.1
    - pillow==11.3.0
    - proglog==0.1.12
    - protobuf==6.33.4
    - psutil==7.2.1
    - pyflame==0.3.2
    - pygame==2.6.1
    - pyparsing==3.3.1
    - pytablewriter==1.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - requests==2.32.5
    - rich==14.2.0
    - rl_zoo3==2.6.0
    - sb3_contrib==2.6.0
    - scipy==1.17.0
    - seaborn==0.13.2
    - simplejson==3.20.2
    - six==1.17.0
    - stable_baselines3==2.6.0
    - tabledata==1.3.4
    - tcolorpy==0.1.7
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tensorstore==0.1.80
    - toolz==1.1.0
    - treescope==0.1.10
    - typepy==1.3.4
    - tzdata==2025.3
    - urllib3==2.6.3
    - wasabi==1.1.3

